spring:
  application:
    name: job-engine-spring
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: job-engine-spring
        version: 0.1.0
        type: SYNC
        stdio: true
        annotation-scanner:
          enabled: true
  datasource:
    url: ${JOB_ENGINE_POSTGRES_URL:jdbc:postgresql://localhost:5432/job_engine}
    username: ${JOB_ENGINE_POSTGRES_USER:}
    password: ${JOB_ENGINE_POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: profile
    schemas:
      - profile
      - document
      - job_schema
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: OFF
